#!/usr/bin/env bash
# DO NOT EDIT THIS FILE

wordArray=(
    'Hallo'
    'Guten Tag'
    'Danke'
    'Dankeschön'
    'Vielen Dank'
    'Tausend Dank'
    'Bitte'
    'Gut'
    'tschüss'
    'Apfel'
    'Mann'
    'Frau'
    'Junge'
    'Mädchen'
    'Ihr'
    'Ein Mann'
    'Eine Frau'
    'Ein Junge'
    'Ein Mädchen'
    'Gern Geschehen'
    'Gerne'
    'Es tut mir Leid'
    'Essen'
    'Isst'
    'Esse'
    'Esst'
)
meaningArray=(
    "Hello, a greeting"
    "Good Day"
    "Thanks / Thank you"
    "Thank you very much"
    "Many Thanks"
    "A Thousand Thanks"
    "Please"
    "Good / Fine"
    "Bye"
    "Apple"
    "Man"
    "Woman"
    "Boy"
    "Girl"
    "You / Her"
    "A man"
    "A woman"
    "A boy"
    "A girl"
    "You're Welcome"
    "A less formal 'You're Welcome'"
    "I'm sorry, or literally translated 'It does me Harm'"
    "Are Eating"
    "Are Eating / Eats"
    "Am Eating / Eat / Eating"
    "Are Eating / Eating / Eat"
)
pronunciationArray=(
    'ha-low'
    'gu-ten tag'
    'dahn-keh'
    'dahn-keh-show-n'
    'Feel-en Dahnk'
    't-ow-zend Dahnk'
    'bit-teh'
    'goo-t'
    'choosse'
    'app-fel'
    'mah-n'
    'frow'
    'you-n-geh'
    'maid-ken'
    'e-hr'
    'eye-n Man'
    'eye-neh frow'
    'eye-n you-n-geh'
    'eye-n maid-ken'
    'Ghern gah-shane'
    'Ghern'
    'Es toot meir lied'
    'es-sen'
    'isst'
    'es-seh'
    'esst'
)
export wordArray
export meaningArray
export pronunciationArray
# chmod +x ~/.vocab-script
. ~/.vocab-script-de
exit 0
