#!/usr/bin/env bash
# DO NOT EDIT THIS FILE

wordArray=(
    'Hallo'
    'Guten Tag'
    'Danke'
    'Bitte'
    'Gut'
    'tschüss'
    'Apfel'
    'Mann'
    'Frau'
    'Junge'
    'Mädchen'
    'Ihr'
    'Ein Mann'
    'Eine Frau'
    'Ein Junge'
    'Ein Mädchen'
    'Gern Geschehen'
)
meaningArray=(
    "Hello, a greeting"
    "Good Day"
    "Thank you"
    "Please"
    "Good / Fine"
    "Bye"
    "Apple"
    "Man"
    "Woman"
    "Boy"
    "Girl"
    "You / Her"
    "A man"
    "A woman"
    "A boy"
    "A girl"
    "You're Welcome"
)
pronunciationArray=(
    'ha-low'
    'gu-ten tag'
    'dahn-keh'
    'bit-teh'
    'goo-t'
    'choosse'
    'app-fel'
    'mah-n'
    'frow'
    'you-n-geh'
    'maid-ken'
    'e-hr'
    'eye-n Man'
    'eye-neh frow'
    'eye-n you-n-geh'
    'eye-n maid-ken'
    'Ghern gah-shane'
)
export wordArray
export meaningArray
export pronunciationArray
# chmod +x ~/.vocab-script
. ~/.vocab-script-de
exit 0
