#!/usr/bin/env bash
# DO NOT EDIT THIS FILE

wordArray=( 'Hallo' 'Guten Tag' 'Danke')
meaningArray=( "Hello, a greeting" "Good Day" "Thank you")
pronunciationArray=("ha-low" "gu-ten tag" "DAHN-keh")
export wordArray
export meaningArray
export pronunciationArray
# chmod +x ~/.vocab-script
. ~/.vocab-script-de
exit 0
